# Introduction  
Medical decisions typicaly require patients and health care providers to weigh the pros and cons of multiple outcomes.
Within a rational decisoin making framework, this process should take the form of a quantitative weighing of the risk of events multiplied by the desirability or undesirability of the event happening.
In even the simple case of two outomes, this process is challenging when decision makers would like to take account of uncertainty in estimates of both outcomes.
Difficulty increases as the numbe rof outcomes to consider increase, and the process can quickly become overwhelming.
Further complications arise when estimates are generalized to new settings where baseline event rates may differ substantially, requiring new calculations.  

A number of alternatives exist within the literature aimed at addressing the issue of optimizing treatment selection in the case of multiple outcomes and incorporating uncertainty.
Reviews assessed within the GRADE framework present outcomes in terms of absolute risk reductions alongside their relative reduction counterparts. 
Qualitative multi-criteria decision aids walk patients through a process of preference elicitation for relevant outcomes.
Preference statements typicaly take the form of likert scales, whose results are then summed and qualitatively assessed.
In some cases, these tools are made crudely quantitative through the multiplication of the preference score by the proability of the event and then summing these values.
Since the tenants of decision theory suggest that the optimal decision is the one that maximizes expected utility, this process should be provide reasonable decisions.
At the most extreme end of the complexity front are methods developed by **XXX** which are embedded within meta-analysis themselves and fully account for uncertainty in ranking, base rates, and relative effects.
While this method is attractive from the standpoint of rigour, it can only feasibly be conducted by an expert team, and provides a set of decision weights specific to that team.
The issue becomes, for example, when a new clinician in a new setting wishes to adapt these wieghts to their own patients.  
  
Network meta-analyses are a relatively novel synthesis paradigm that allow for all relevant treatments within a connected network to be compared by combining both direct and indirect information.
When a treatment comparison contains both direct and indirect copmarison information, network meta-analyses can provide more precise estimates than had the comparison been made based only on the direct comparison.
Since NMAs consider all relevant comparators for a given indication, they are attractive for aiding decision making directly.
This benefit is further realized by the ability of NMAs to output probabilistic outcomes such as the Surface under the cumulative ranking curve (SUCRA) which places all treatments on the same scale and allows for simple calculatoins for guiding treatment.

Recently, researchers from the London School of Economics developed an interactive decision aid for patients considering statins. The tool is based on the SUCRA output of an NMA, which is weighted by the normalized preferences indicated by patients. While the tool is attractive, it has major theoretical limitations owing to both the insenvitivity of SUCRA to baseline event rates as well as the potential instability of SUCRA itself.
First, since SUCRA is based on treatment rankings, treatment weights applied to this outcome will not reflect potentially large difference in the absolute rates of events. Second, SUCRA is typically calculated based on relative effects which themselves can artificially inflate underlying absolute rates. 
SUCRA further magnifies even small differences in relative risks, potentially overstating the certainty with which one intervention is meaninfully better than another.  
  
The purpose of this project was to develop a simple web based application to facilitate using the results of an NMA or other synthesis product for decicision making accounting for uncertainty. We then compare this approach to decisions based on SUCRA using a recently conducted NMA of treatments for Patent Ductus Arteriosus.  
